name: Daily Tender Crawler

on:
  schedule:
    - cron: '0 4 * * *' # UTC 04:00 = 台灣時間 12:00
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium python-docx
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        # 獲取 Chrome 版本並下載匹配的 ChromeDriver
        CHROME_VERSION=$(google-chrome --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
        echo "Detected Chrome version: $CHROME_VERSION"
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        echo "Installing ChromeDriver version: $CHROMEDRIVER_VERSION"
        wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        chromedriver --version
    - name: Run crawler
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
      run: python tender_crawler.py
    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tender-results
        path: '*.docx'
